name: example
description: A Flutter example project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sliding_drawer:
    path: ../
  
dev_dependencies:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
