name: sliding_drawer
version: 1.0.2
description: A Flutter widget that provides a drawer with the sliding effect.
homepage: https://github.com/ilia-korolev/sliding_drawer
repository: https://github.com/ilia-korolev/sliding_drawer
documentation: https://github.com/ilia-korolev/sliding_drawer
issue_tracker: https://github.com/ilia-korolev/sliding_drawer/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0
